// Ordre du Pokédex Génération 1 (#001 → #151), noms français
// Correspondance : nom EN → nom FR utilisé dans /public/monsters/
export const MONSTER_NAMES: string[] = [
  "Bulbizarre",  // 001 Bulbasaur
  "Herbizarre",  // 002 Ivysaur
  "Florizarre",  // 003 Venusaur
  "Salamèche",   // 004 Charmander
  "Reptincel",   // 005 Charmeleon
  "Dracaufeu",   // 006 Charizard
  "Carapuce",    // 007 Squirtle
  "Carabaffe",   // 008 Wartortle
  "Tortank",     // 009 Blastoise
  "Chenipan",    // 010 Caterpie
  "Chrysacier",  // 011 Metapod
  "Papilusion",  // 012 Butterfree
  "Aspicot",     // 013 Weedle
  "Coconfort",   // 014 Kakuna
  "Dardargnan",  // 015 Beedrill
  "Roucool",     // 016 Pidgey
  "Roucoups",    // 017 Pidgeotto
  "Roucarnage",  // 018 Pidgeot
  "Rattata",     // 019 Rattata
  "Rattatac",    // 020 Raticate
  "Piafabec",    // 021 Spearow
  "Rapasdepic",  // 022 Fearow
  "Abo",         // 023 Ekans
  "Arbok",       // 024 Arbok
  "Pikachu",     // 025 Pikachu
  "Raichu",      // 026 Raichu
  "Sabelette",   // 027 Sandshrew
  "Sablaireau",  // 028 Sandslash
  "Nidoran♀",   // 029 Nidoran♀
  "Nidorina",    // 030 Nidorina
  "Nidoqueen",   // 031 Nidoqueen
  "Nidoran♂",   // 032 Nidoran♂
  "Nidorino",    // 033 Nidorino
  "Nidoking",    // 034 Nidoking
  "Mélofée",     // 035 Clefairy
  "Mélodelfe",   // 036 Clefable
  "Goupix",      // 037 Vulpix
  "Feunard",     // 038 Ninetales
  "Rondoudou",   // 039 Jigglypuff
  "Grodoudou",   // 040 Wigglytuff
  "Nosferapti",  // 041 Zubat
  "Nosferalto",  // 042 Golbat
  "Mystherbe",   // 043 Oddish
  "Ortide",      // 044 Gloom
  "Rafflesia",   // 045 Vileplume
  "Paras",       // 046 Paras
  "Parasect",    // 047 Parasect
  "Mimitoss",    // 048 Venonat
  "Aéromite",    // 049 Venomoth
  "Taupiqueur",  // 050 Diglett
  "Triopikeur",  // 051 Dugtrio
  "Miaouss",     // 052 Meowth
  "Persian",     // 053 Persian
  "Psykokwak",   // 054 Psyduck
  "Akwakwak",    // 055 Golduck
  "Férosinge",   // 056 Mankey
  "Colossinge",  // 057 Primeape
  "Caninos",     // 058 Growlithe
  "Arcanin",     // 059 Arcanine
  "Ptitard",     // 060 Poliwag
  "Têtarte",     // 061 Poliwhirl
  "Tartard",     // 062 Poliwrath
  "Abra",        // 063 Abra
  "Kadabra",     // 064 Kadabra
  "Alakazam",    // 065 Alakazam
  "Machoc",      // 066 Machop
  "Machopeur",   // 067 Machoke
  "Mackogneur",  // 068 Machamp
  "Chétiflor",   // 069 Bellsprout
  "Empiflor",    // 070 Weepinbell
  "Boustiflor",  // 071 Victreebel
  "Tentacool",   // 072 Tentacool
  "Tentacruel",  // 073 Tentacruel
  "Racaillou",   // 074 Geodude
  "Gravalanch",  // 075 Graveler
  "Grolem",      // 076 Golem
  "Ponyta",      // 077 Ponyta
  "Galopa",      // 078 Rapidash
  "Ramoloss",    // 079 Slowpoke
  "Flagadoss",   // 080 Slowbro
  "Magnéti",     // 081 Magnemite
  "Magnéton",    // 082 Magneton
  "Canarticho",  // 083 Farfetch'd
  "Doduo",       // 084 Doduo
  "Dodrio",      // 085 Dodrio
  "Otaria",      // 086 Seel
  "Lamantine",   // 087 Dewgong
  "Tadmorv",     // 088 Grimer
  "Grotadmorv",  // 089 Muk
  "Kokiyas",     // 090 Shellder
  "Crustabri",   // 091 Cloyster
  "Fantominus",  // 092 Gastly
  "Spectrum",    // 093 Haunter
  "Ectoplasma",  // 094 Gengar
  "Onix",        // 095 Onix
  "Soporifik",   // 096 Drowzee
  "Hypnomade",   // 097 Hypno
  "Krabby",      // 098 Krabby
  "Krabboss",    // 099 Kingler
  "Voltorbe",    // 100 Voltorb
  "Électrode",   // 101 Electrode
  "Noeunoeuf",   // 102 Exeggcute
  "Noadkoko",    // 103 Exeggutor
  "Osselait",    // 104 Cubone
  "Ossatueur",   // 105 Marowak
  "Kicklee",     // 106 Hitmonlee
  "Tygnon",      // 107 Hitmonchan
  "Excelangue",  // 108 Lickitung
  "Smogo",       // 109 Koffing
  "Smogogo",     // 110 Weezing
  "Rhinocorne",  // 111 Rhyhorn
  "Rhinoféros",  // 112 Rhydon
  "Leveinard",   // 113 Chansey
  "Saquedeneu",  // 114 Tangela
  "Kangourex",   // 115 Kangaskhan
  "Hypotrempe",  // 116 Horsea
  "Hypocéan",    // 117 Seadra
  "Poissirène",  // 118 Goldeen
  "Poissoroy",   // 119 Seaking
  "Stari",       // 120 Staryu
  "Staross",     // 121 Starmie
  "M. Mime",     // 122 Mr. Mime
  "Insécateur",  // 123 Scyther
  "Lippoutou",   // 124 Jynx
  "Élektek",     // 125 Electabuzz
  "Magmar",      // 126 Magmar
  "Scarabrute",  // 127 Pinsir
  "Tauros",      // 128 Tauros
  "Magicarpe",   // 129 Magikarp
  "Léviator",    // 130 Gyarados
  "Lokhlass",    // 131 Lapras
  "Métamorph",   // 132 Ditto
  "Évoli",       // 133 Eevee
  "Aquali",      // 134 Vaporeon
  "Voltali",     // 135 Jolteon
  "Pyroli",      // 136 Flareon
  "Porygon",     // 137 Porygon
  "Amonita",     // 138 Omanyte
  "Amonistar",   // 139 Omastar
  "Kabuto",      // 140 Kabuto
  "Kabutops",    // 141 Kabutops
  "Ptéra",       // 142 Aerodactyl
  "Ronflex",     // 143 Snorlax
  "Artikodin",   // 144 Articuno
  "Électhor",    // 145 Zapdos
  "Sulfura",     // 146 Moltres
  "Minidraco",   // 147 Dratini
  "Draco",       // 148 Dragonair
  "Dracolosse",  // 149 Dragonite
  "Mewtwo",      // 150 Mewtwo
  "Mew",         // 151 Mew
];
